version: '3.5'

services:
  app:
    build:
      context: ""
      dockerfile: Dockerfile.local
    ports:
      - "8000:80"
    networks:
      local-network:
        aliases:
          - rh-lookup
    container_name: rh-lookup
    environment:
      LISTEN_ADDRESS: :80
      WAIT_HOSTS:

networks:
  local-network:
    external:
      name: rh-local-network

