FROM golang:1.12.5

ENV PROJECT_DIR /go/lookup
ENV BIN_DIR /go/bin

RUN mkdir -p $PROJECT_DIR
ADD . $PROJECT_DIR
WORKDIR $PROJECT_DIR

## Add the wait script to the image
ADD wait /wait
RUN chmod +x /wait

ENV GOPATH /go
ENV GO111MODULE=on

RUN go mod download && go build -o $BIN_DIR/lookup $PROJECT_DIR/cmd/lookup/main.go

CMD /wait && $BIN_DIR/lookup
